name: 'xcresulttool'
description: 'generates a human-readable test report from the Xcode result bundle and shows it on GitHub Checks.'
author: 'kishikawa katsumi'
inputs:
  xcresult:
    required: true
    description: 'Path to the xcresult bundle'
runs:
  using: 'node12'
  main: 'dist/index.js'
